const interactionIds = {
  SETUP_MODAL_ID: 'setup-modal',
  SETUP_VIEW_HOME_ID: 'setup-view-home',
  SETUP_VIEW_DISCORD_ID: 'setup-view-discord',
  SETUP_VIEW_PLAYER_TOOLS_ID: 'setup-view-player-tools',
  SETUP_VIEW_MAYOR_ID: 'setup-view-mayor',
  SETUP_VIEW_EVENT_REMINDERS_ID: 'setup-view-event-reminders',
  SETUP_VIEW_MOD_UPDATES_ID: 'setup-view-mod-updates',
  SETUP_MAYOR_EDIT_ID: 'setup-mayor-edit',
  SETUP_FAST_SETUP_ID: 'setup-fast-setup',
  SETUP_EVENT_REMINDERS_MODAL_ID: 'setup-event-reminders-modal',
  SETUP_EVENT_REMINDERS_TEST_ALL_ID: 'setup-event-reminders-test-all',
  SETUP_MAYOR_TOGGLE_ELECTION_PING_ID: 'setup-mayor-toggle-election-ping',
  SETUP_MAYOR_TOGGLE_CHANGE_PING_ID: 'setup-mayor-toggle-change-ping',
  SETUP_MAYOR_RELOAD_ID: 'setup-mayor-reload',
  SETUP_MAYOR_RESET_ID: 'setup-mayor-reset',
  SETUP_MOD_UPDATES_MODAL_ID: 'setup-mod-updates-modal',
  SETUP_MOD_UPDATES_REFRESH_ID: 'setup-mod-updates-refresh',
  SETUP_MOD_UPDATES_TEST_ID: 'setup-mod-updates-test',
  SETUP_VIEW_REACTION_ROLES_ID: 'setup-view-reaction-roles',
  SETUP_VIEW_SHITTER_ID: 'setup-view-shitter',
  SETUP_REACTION_ADD_MODAL_ID: 'setup-reaction-add-modal',
  SETUP_REACTION_REMOVE_MODAL_ID: 'setup-reaction-remove-modal',
  SETUP_SHITTER_MODAL_ID: 'setup-shitter-modal',
  SETUP_REACTION_CHANNEL_INPUT_ID: 'setup-reaction-channel-id',
  SETUP_REACTION_MESSAGE_INPUT_ID: 'setup-reaction-message-id',
  SETUP_REACTION_ROLE_INPUT_ID: 'setup-reaction-role-id',
  SETUP_REACTION_EMOJI_INPUT_ID: 'setup-reaction-emoji',
  SETUP_REACTION_REQUIRED_ROLE_INPUT_ID: 'setup-reaction-required-role-id',
  SETUP_SHITTER_BLOCKED_USERS_INPUT_ID: 'setup-shitter-blocked-users',
  SETUP_SHITTER_BLOCKED_ROLES_INPUT_ID: 'setup-shitter-blocked-roles',
  SETUP_SHITTER_ALLOWED_ROLES_INPUT_ID: 'setup-shitter-allowed-roles',
  SETUP_MOD_UPDATES_CHANNEL_INPUT_ID: 'setup-mod-updates-channel-id',
  SETUP_MOD_UPDATES_ROLE_INPUT_ID: 'setup-mod-updates-role-id',
  SETUP_MOD_UPDATES_REPOS_INPUT_ID: 'setup-mod-updates-repos',
  SETUP_EVENT_REMINDERS_CHANNEL_INPUT_ID: 'setup-event-reminders-channel-id',
  SETUP_EVENT_REMINDERS_ROLES_INPUT_ID: 'setup-event-reminders-roles',
  SETUP_CHANNEL_INPUT_ID: 'setup-channel-id',
  SETUP_ROLE_INPUT_ID: 'setup-role-id'
};

module.exports = { interactionIds };
